apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ledger-writer-hpa
  namespace: bank-of-anthos
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ledgerwriter
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
