apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: bandwidth-limit
spec:
  action: bandwidth
  mode: all
  selector:
    namespaces:
      - bank-of-anthos
    labelSelectors:
      app: frontend 
  bandwidth:
    rate: "10kbps"
    limit: 1000
    buffer: 10000
  duration: "2m"

